export const tableStructure = [
  {
    method: "text",
    type: "text",
    name: "country",
    maxLength: null,
    nullable: false,
  },
  {
    method: "integer",
    type: "integer",
    name: "year",
    maxLength: null,
    nullable: false,
  },
  {
    method: "text",
    type: "text",
    name: "artists",
    maxLength: null,
    nullable: false,
  },
  {
    method: "text",
    type: "text",
    name: "song",
    maxLength: null,
    nullable: false,
  },
  {
    method: "text",
    type: "text",
    name: "url",
    maxLength: null,
    nullable: false,
  },
  {
    method: "string",
    type: "character varying",
    name: "duration",
    maxLength: 5,
    nullable: false,
  },
  {
    method: "text",
    type: "text",
    name: "image",
    maxLength: null,
    nullable: true,
  },
  {
    method: "boolean",
    type: "boolean",
    name: "finalist",
    maxLength: null,
    nullable: false,
  },
  {
    method: "boolean",
    type: "boolean",
    name: "winner",
    maxLength: null,
    nullable: false,
  },
];
