export const playlistURL =
  "https://www.youtube.com/watch?v=M_kTSBqQkME&list=PL0ufFt_EF0lmzcV1Tx6g0fjqtu20dOWk2";
export const defaultThumbnail =
  "https://millennialdiyer.com/wp1/wp-content/uploads/2018/11/Tips-Tricks-for-Assigning-Album-Cover-Art-to-your-Music-Library-Default-Image.jpg";
export const prostii = [
  "MV",
  "M\\V",
  "HD",
  "HQ",
  "HIT",
  "\\+18",
  "MUSIC VIDEO",
  "OFFICIAL VIDEO",
  "Official Video",
  "Official",
  "720p",
  "1070p",
  "4K",
  "official",
  "video clip",
  "NEW",
  "LYRICS",
  "LYRIC",
  "VIDEO",
  "lyrics",
  "lyric",
  "video",
  "audio",
  "manele",
  "vechi",
  "de  dragoste",
  "- Hit",
  "k-play",
  "karaoke",
  "KARAOKE",
  "CBX",
  " oficial",
  "5K",
  "8K",
  "16K",
  "HiT",
  " Oficial",
  "█▬█ █ ▀█▀",
].join("|");
