export const defaultPlaylistURL =
  // "https://www.youtube.com/watch?v=uiH4BFTELME&list=PL9KifGoS3P-TWwlbEx7OYjstrBHgpdm7z";
  // "https://www.youtube.com/playlist?list=PLuXpx63rTncKxZZmZ9aOh8UeUJrxIfSuM";
  // "https://www.youtube.com/playlist?list=PL84s1Ny_XcUP9MkvA8yf_U17lTATEklPU";
  // "https://www.youtube.com/watch?v=VbNFep0qyck&list=PLOyhhO9Lb2z17C3KoHsIvahbWhcxTBo8w";
  "https://www.youtube.com/playlist?list=PL15B1E77BB5708555";
export const defaultThumbnail = "https://i.imgur.com/O21q7aE.png";
// "https://millennialdiyer.com/wp1/wp-content/uploads/2018/11/Tips-Tricks-for-Assigning-Album-Cover-Art-to-your-Music-Library-Default-Image.jpg";

const eurovisionCountries = [
  "Albania",
  "Andorra",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Belarus",
  "Belgium",
  "Bosnia & Herzegovina",
  "Bosnia and Herzegovina",
  "Bosnia",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France ",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Israel",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Morocco",
  "The Netherlands",
  "Netherlands",
  "North Macedonia",
  "F\\.Y\\.R Macedonia",
  "F\\.Y\\.R",
  "FYR",
  "Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "San Marino",
  "SanMarino",
  "Serbia & Montenegro",
  "Serbia and Montenegro",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Espa(?:ñ|n)a",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "United Kingdom",
  "Yugoslavia",
].join("|");

// const eurovisionCountriesAllCases = [
//   ...eurovisionCountries,
//   ...eurovisionCountries.map((country) => country.toLowerCase()),
//   ...eurovisionCountries.map((country) => country.toUpperCase()),
// ];

/// TREBUIE INSVERSAT TOT PUS CELE MAI EXPLICITE LA FINAL ASTA E

const prostiiOricumOnlyFirstCap = [
  "Live At",
  "(?:At|At\\s*The|The)?\\s*?(?:Grand)?\\s*?Final",
  "(?:At|At\\s*The|The)?\\s*?(?:Of\\s*The|Of|The)?\\s*?Eurovision\\s*Song\\s*Contest",
  "Eurovision\\s*Winner",
  "Eurovision",
  "Winner(?:[\\s-:#+./]|$)",
  "(?:At|At\\s*The|The)?\\s*?(?:1St|First|2Nd|Second)?\\s*?Semi\\s*?-?\\s*?final\\s*?(?:1|2)?",
  "(?:At|At\\s*The|The)?\\s*?(?:1St|First|2Nd|Second)?\\s*?S\\s*?-?\\s*?F\\s*?(?:1|2)?(?:[\\s-:#+./]+|$)",
  // "(?:At|At\\s*The|The)?\\s*?(?:1St|First|2Nd|Second)?\\s*?Semi-final\\s*?(?:1|2)?",
  // "(?:At|At\\s*The|The)?\\s*?(?:1St|First|2Nd|Second)?\\s*?Semi\\s*Final\\s*?(?:1|2)?",
  // "(?:At|At\\s*The|The)?\\s*?Semifinal",
  // "(?:At|At\\s*The|The)?\\s*?Semi-final",
  // "(?:At|At\\s*The|The)?\\s*?Semi\\s*Final",
  // "(?:At|At\\s*The|The)?\\s*?Sf\\s*?(?:1|2)",
  "1St",
  "2Nd",
  "ESC(?:[\\s-:#+./]|$)",
  "Interval Act",
  "Videoclip Oficial",
  "#uASAP",
  "Official Video",
  "Offical Video",
  "Video Official",
  "Video Oficial",
  "Official Music Video",
  "Music Video",
  "Official M/v",
  "M/v",
  "Official Mv",
  "Mv",
  "remixata",
  "Remix",
  "Uncensored Version",
  "Hd",
  "BRIT Awards",
  "by Method Studios",
  "- Official",
  "Shot By.*",
  "Manele Vechi De Dragoste",
  "Manele Vechi",
  "Manele Noi",
  "Clip Original",
  "4K",
  "International Hits",
  "Oficial Video Live",
  "Oficial Video Nou",
  "Oficial Video",
  "Official Video",
  "New Hit",
  "Oficial Hit",
  "Original Video",
  "Original Audio",
  "Oficial Audio",
  "Official Audio",
  "Videoclip Oficial",
  "Videoclip Original",
  "Audio Oficial",
  "Audio Original",
  "Videoclip",
  "Clip Oficial",
  "Clip Official",
  "Clip Original",
  "Remake",
  "Cbx",
  "5K",
  "720P",
  "1080P",
  "High Definition",
  "Hd",
  "Hq",
  "Lyric",
  "Manele De Dragoste ?(?:Vechi)?",
  "K-play",
  "Karaoke",
  "8K",
  "16K",
  "Manele",
  "Radio Edit",
  "Songs With Live Music",
  "Songs With Live Orchestra",
  "With Orchestra",
  "Bonus Track",
  "Vevo",
  "Teaser",
  "Main Stage",
  "Audio(?:[\\s-:#+./]|$)",
  "Video",
  "With Interruption",
  "██▬█ █ ▀█▀ ?forever",
  "█▬█ █ ▀█▀",
  "Brødrene Olsen",
  "copenhage",
  "ZOOM STUDIO",
  "Ultra Mix",
  "Super Hit",
  "Mega Hit",
  "Oficial LiveMix",
  "RoTerra Music",
  "CLIP EXCLUSIV",
  "Hit de Hit",
  "NOU NOU NOU",
  "#DESANTOMUSIC",
  "& 3D",
  "Etno Tv",
  "@DanBursucOfficial",
  "xvid",
  "YouTube",
  "Beautiful Trance",
  "Nas Napi",
  "aniversare Culiță",
  "aniversare Culita",
  "parodie",
  "colaj de petrecere",
  "colaj etno",
  "colaj",
  "muzica de petrecere populara",
  "muzica de petrecere",
  "muzica populara",
  "@ Club Tranquila",
  "MagicSoundOfficial",
  "byDanielCameramanu",
  "HITUL ANULUI",
  "DVD",
  "Etno star 4",
  "Fara dedicatii",
  "NECENZURATA",
  "first hit single",
  "first single",
  "Pt\\.?\\s?\\d*[\\s-:#+./]*\\d*",
  "Part\\s?\\d*[\\s-:#+./]*\\d*",
  "Day version",
  "Night version",
  "Furious 7 Soundtrack",
  "Soundtrack",
].join("|");
// const prostiiOricumAllCaps = prostiiOricumOnlyFirstCap.map((string) =>
//   string.toUpperCase()
// );
// const prostiiOricumLowercase = prostiiOricumOnlyFirstCap.map((string) =>
//   string.toLowerCase()
// );
// const prostiiOricumAllCases = [
//   ...prostiiOricumOnlyFirstCap,
//   ...prostiiOricumAllCaps,
//   ...prostiiOricumLowercase,
// ];
export const prostiiFix = [
  "CONTACT.*",
  "- :",
  "Live(\\W|$)",
  "\\d{1,3}p(?:([\\s-:#+./]|$)|$)",
  "^\\d{1,2}\\.",
  "HiT",
  "OFFICIAL",
  "\\|",
  "-!",
  "4:3",
  "5:4",
  "16:9",
  "16:10",
  "21:9",
  "\\+18",
  "STEREO",
  "\\((?:1|2)\\)",
  "\\|(?:\\s|$)",
].join("|");

export const unwantedChannels = [
  "Radio Nostalgia",
  "NRK",
  "klausciusca",
  "Roster Music",
  "Cat Music",
  "Texhnician",
  "Fueled By Ramen",
  "Big Hit Labels",
  "EOPGlobalInvestment",
  "Emy Me",
  "Oscar8765",
  "escfan1",
  "Victor Ovies",
  "escLIVEmusic1",
  "escLIVEmusic",
  "MusicOfTheWorld2008",
  "unaicuatro",
  "EurovisionGR",
  "webuvision",
  "NexttimeBand",
  "mozpiano2",
  "WORLDSTARHIPHOP",
  "Nek Music Tv",
  "Claudia Oficial Music",
  "AutenticMusicRomania",
  "AmmA Music & Sound",
  "ugnal",
  "KreativeFotoVideo",
  "Livia Pop Official",
  "jupanul32",
  "xhesjan durresi",
  "Sound EmpireTDM",
  "MusicMondoRomania",
  "Stana Stepanu",
  "Cioc Music",
  "magaionut",
  "p.j. u",
  "CrewetzelEvents",
  "MUZICA POPULARA RMG",
  "MT Record",
  "ZENYS OFFICIAL",
  "Dani Mocanu © Oficial",
  "Jean de la Craiova",
  "retroswagga2",
  "Sexy25Diva",
  "12cgr",
  "Walt Disney Animation Studios",
  "GoodClipsDaily",
  "Spinnin' Records",
];

export const prostii = `${unwantedChannels.join(
  "|"
)}|${prostiiOricumOnlyFirstCap}|(?:${eurovisionCountries})(?:[\\s-:#+./]*|$)`;
// [
//   ...prostiiOricumOnlyFirstCap,
//   ...eurovisionCountries,
// ].join("|");
// export const prostii = [
//   ...prostiiOricumAllCases,
//   ...eurovisionCountriesAllCases,
// ].join("|");

//Check if song description contains auto generated by youtube so you know its not a random channel

const finalRegExs = [
  "at the of",
  "[\\s-:#+./]*?New[\\s-:#+./]*$",
  "[\\s-:#+./]*?Hit[\\s-:#+./]*$",
  "[\\s-:#+./]*?Oficial[\\s-:#+./]*$",
  "[\\s-:#+./]*?The Original[\\s-:#+./]*$",
  "[\\s-:#+./]*?Original[\\s-:#+./]*$",
  "[\\s-:#+./]*?Bomba[\\s-:#+./]*$",
  "[\\s-:#+./]*?Cover[\\s-:#+./]*$",
  "[\\s-:#+./]?(?:0?(?:1|2))[\\s-:#+./]*$",
  "[\\s-:#+./]+?Live[\\s-:#+./]*$",
  "^[\\s-:#+./]*?LIVE",
  "^[\\s-:#+./]*",
  "[\\s-:#+./]*$",
  "[\\s-:#+./]07.*$",
  "[\\s-:#+./]FULL[\\s-:#+./]*$",
  "[\\s-:#+./]CLIP[\\s-:#+./]*$",
  "[\\s-:#+./]NOU[\\s-:#+./]*$",
  "[\\s-:#+./]New[\\s-:#+./]*$",
  "[\\s-:#+./]Episodul[\\s-:#+./]*$",
  "[\\s-:#+./]Originala[\\s-:#+./]*$",
  "[\\s-:#+./]JALE[\\s-:#+./]*$",
  "(?<=[^d])[\\s-:#+./]by[\\s-:#+./].{1,16}$",
  "(?<=Eminem)Music$",
  '"',
  "@",
];
export const final = (string) => {
  let finalString = string;
  for (const finalRegEx of finalRegExs) {
    finalString = finalString.replace(RegExp(finalRegEx, "gi"), "");
  }
  return finalString;
};
